cart/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path(r'^$', views.cart_detail, name='cart_detail'),
    path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

iShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('main.urls')),
    path('sup', include('products.urls')),
    path('cart', include(('cart.urls', 'cart'), namespace='cart')),
    path('checkout', include('checkout.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)    
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Products
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

 
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')
 
def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "main/base.html" %}
{% block title %}Cart{% endblock title %}
{% block nav %}
  {% include 'main/nav-noanim.html' %}
{% endblock nav %}
{% block body %}
<div class="bg-white py-6 sm:py-8 lg:py-12">
    <div class="max-w-screen-lg px-4 md:px-8 mx-auto">
      <div class="mb-6 sm:mb-10 lg:mb-16">
        <h2 class="text-gray-800 text-2xl lg:text-3xl font-bold text-center mb-4 md:mb-6 animate__animated animate__backInDown">Your Cart</h2>
      </div>
      {% if cart|length == 0 %}
        <figure class="flex flex-col items-center justify-center p-8 text-center bg-white border-b border-gray-200 rounded-t-lg md:rounded-t-none md:rounded-tl-lg md:border-r dark:bg-gray-800 dark:border-gray-700 animate__animated animate__zoomIn">
          <blockquote class="max-w-2xl mx-auto mb-4 text-gray-500 lg:mb-8 dark:text-gray-400">
              <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Very easy this was to integrate</h3>
              <p class="my-4 font-light">If you care for your time, I hands down would go with this."</p>
          </blockquote>
          <figcaption class="flex items-center justify-center space-x-3">
              <img class="rounded-full w-9 h-9" src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/karen-nelson.png" alt="profile picture">
              <div class="space-y-0.5 font-medium dark:text-white text-left">
                  <div>Bonnie Green</div>
                  <div class="text-sm font-light text-gray-500 dark:text-gray-400">Developer at Open AI</div>
              </div>
          </figcaption>    
        </figure>
      {% endif %}
      {% if cart|length != 0 %}
      <div class="flex flex-col sm:border-t sm:border-b sm:divide-y mb-5 sm:mb-8">
        <!-- product - start -->
        {% for item in cart %}
        {% with product=item.product %} 
        <div class="py-5 sm:py-8">
          <div class="flex flex-wrap gap-4 lg:gap-6 sm:py-2.5">
            <div class="sm:-my-2.5">
              <a href="{{ product.get_absolute_url }}" class="group w-24 sm:w-40 h-40 sm:h-56 block bg-gray-100 rounded-lg overflow-hidden relative">
                <img src="{{product.img.url}}" loading="lazy" class="w-full h-full object-cover object-center group-hover:scale-110 transition duration-200" />
              </a>
            </div>  
            <div class="flex flex-col justify-between flex-1">
              <div>
                <a href="/product/{{ product.get_absolute_url }}" class="inline-block text-gray-800 hover:text-gray-500 text-lg lg:text-xl font-bold transition duration-100 mb-1">{{ product.title }}</a>
                <span class="block text-gray-500">Amount: {{ item.quantity }}</span>
              </div>  
              <div>
                <span class="block text-gray-800 md:text-lg font-bold mb-1">{{ item.price }}</span> 
                <span class="flex items-center text-gray-500 text-sm gap-1">
                  <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                  </svg>
                  In stock
                </span>
              </div>
            </div>  
            <div class="w-full sm:w-auto flex justify-between border-t sm:border-none pt-4 sm:pt-0">
              <div class="flex flex-col items-start gap-2">
                <a class="pt-3 text-red-500 hover:text-red-700 active:text-red-900 font-semibold select-none transition duration-100"
                   href="{% url "cart:cart_remove" product.id%}">Remove</a>
              </div>  
              <div class="pt-3 sm:pt-2 ml-4 md:ml-8 lg:ml-16">
                <span class="block text-gray-800 md:text-lg font-bold">{{ item.total_price }}</span>
              </div>
            </div>
          </div>
        </div>
        {% endwith %}
      {% endfor %}       
        <!-- product - end -->       
      </div>  
      <!-- totals - start -->
      <div class="flex flex-col items-end gap-4">
        <div class="w-full sm:max-w-xs bg-gray-100 rounded-lg p-4">
          <div class="space-y-1">
          </div>  
          <div class="border-t pt-4 mt-4">
            <div class="flex justify-between items-start text-gray-800 gap-4">
              <span class="text-lg font-bold">Total</span>
              <span class="flex flex-col items-end">
                <span class="text-lg font-bold">${{ cart.get_total_price }}</span>
              </span>
            </div>
          </div>
        </div>
        <a href="{% url "home-page" %}" class="inline-block mt-5 rounded-md bg-zinc-900 px-10 py-2 text-white hover:bg-zinc-800 active:bg-zinc-700">Continue shopping</a>
        <a href="{% url "checkout-form" %}" class="inline-block rounded-md bg-zinc-900 px-10 py-2 text-white hover:bg-zinc-800 active:bg-zinc-700">Check out</a>
      </div>
      <!-- totals - end -->     
      {% endif %}     
    </div>
  </div>
{% endblock body %}