cart/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path(r'^$', views.cart_detail, name='cart_detail'),
    path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

iShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('main.urls')),
    path('sup', include('products.urls')),
    path('cart', include(('cart.urls', 'cart'), namespace='cart')),
    path('checkout', include('checkout.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.MainPage.as_view(), name='home-page'),
    path('<slug:slug>', views.ProductPage.as_view(), name='product_detail'),
    path('contacts', views.contacts, name='contacts-page'),
]

products/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('/add-products', views.AdditionalProductsPage, name='add-products-page'),
]

main/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify
from django.urls import reverse


class Supplier(models.Model):
    
   name = models.CharField('Поставщик', max_length=100)
   address = models.CharField('Адрес', max_length=100)
   tel = models.CharField('Телефон', max_length=10)
   
   def __str__(self):
       return self.name
     
   class Meta:
      verbose_name = 'Поставщик'
      verbose_name_plural = 'Поставщики'
      
        
class Products(models.Model):
      
   title = models.CharField('Название Продукта', max_length=100, unique=True)
   description = models.TextField('Описание Продукта')
   price = models.DecimalField('Цена', max_digits=7, decimal_places=2)
   amount = models.IntegerField('Склад', default=0)
   supplier = models.ForeignKey(Supplier, verbose_name = 'Поставщик', on_delete=models.CASCADE, default=Supplier)
   options_list = (
       ('S', 'Small'),
       ('M', 'Medium'),
       ('L', 'Large'),
   )
   options = models.CharField('Опции', max_length=1, choices=options_list, default='S')
   img = models.ImageField('Фото', default= '', upload_to='products_img')
   slug = models.SlugField(null=False, unique=True, default='')
   
   def get_absolute_url(self):
        return reverse("product_detail", kwargs={"slug": self.slug})
    
   def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs) 
        
   def __str__(self):
       return self.title
     
   class Meta:
      verbose_name = 'Товар'
      verbose_name_plural = 'Товары'
      
    
class Orders(models.Model):
   
   order_number = models.IntegerField('Номер Заказа', default=0)
   date = models.DateTimeField('Дата', default=timezone.now)
   name = models.CharField('Имя', max_length=15)
   surname = models.CharField('Фамилия', max_length=20)
   phone = models.CharField('Телефон', max_length=10)
   email = models.CharField('Email', max_length=20, default='')
   total = models.CharField('Сумма', default='0',max_length=100)
   goods = models.CharField('Товары', max_length =250, default='')
   delivery = models.CharField('Доставка', max_length =250, default='')
   
   def __str__(self):
       return f'Заказ №{self.order_number}'
   
   class Meta:
      verbose_name = 'Заказ'
      verbose_name_plural = 'Заказы'
   

products/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from .models import Products
from cart.forms import CartAddProductForm
from django.views.generic import ListView, DetailView


class MainPage(ListView):
   model = Products
   template_name = 'main/main.html'
   context_object_name = 'products'
   
   def get_context_data(self, **kwargs):
      ctx = super(MainPage, self).get_context_data(**kwargs)
      ctx['title'] = 'Головна сторінка'      
      return ctx
   
class ProductPage(DetailView):
   model = Products
   template_name = 'main/product.html'
   context_object_name = 'product'
   
   def get_context_data(self, **kwargs):
      cart_product_form = CartAddProductForm()
      ctx = super(ProductPage, self).get_context_data(**kwargs)
      ctx['title'] = ''
      ctx['cart_product_form'] = cart_product_form     
      return ctx


def contacts (request):
        
   data = {
      'title': 'Контакти',
   }  
   return render(request, 'main/contacts.html', data)

products/views.py
from django.shortcuts import render
from cart.forms import CartAddProductForm
from django.views.generic import ListView, DetailView


def AdditionalProductsPage (request):
      
   data = {
      'title': 'Доп продукти',
   }  
   return render(request, 'products/products.html', data)

main/templates/main/contacts.html
{% extends 'main/base.html' %}
{% block description %}
  <meta name="description" content="контакты">
{% endblock description %}
{% block title %}{{title}}{% endblock title %}
{% block nav %}
  {% include 'main/nav-noanim.html' %}
{% endblock nav %}
{% block body %}
 <p>Contacts</p>
{% endblock body %}

main/templates/main/main.html
{% extends 'main/base.html' %}
{% block description %}
  <meta name="description" content="краткое описание главной страницы">
{% endblock description %}
{% block title %}{{title}}{% endblock title %}
{% block nav %}
  {% include 'main/nav-anim.html' %}
{% endblock nav %}
{% block body %}
<div class="bg-white py-6 sm:py-8 lg:py-12 lg:mr-20 lg:ml-20">
  <div class="max-w-screen-2xl px-4 md:px-8 mx-auto">
    <div class="flex justify-between items-end gap-4 mb-6">
      <h2 class="text-gray-800 text-2xl lg:text-3xl font-bold">Товары</h2>
    </div>   
    <div class="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 gap-x-4 md:gap-x-6 gap-y-8 lg:gap-x-10 gap-y-20 xl:gap-x-20 gap-y-25">
      <!-- product - start -->      
      {% for product in products %}
      <div>
        <a href="{{ product.get_absolute_url }}" class="group h-80 block bg-gray-100 rounded-lg overflow-hidden relative mb-2 lg:mb-3">
          <img src="{{product.img.url}}" class="w-full h-full object-cover object-center" />
          <span class="bg-red-500 text-white text-sm tracking-wider uppercase rounded-br-lg absolute left-0 top-0 px-3 py-1.5">sale</span>
        </a>
        <div>
          <a href="{{ product.get_absolute_url }}" class="text-gray-500 hover:gray-800 lg:text-lg transition duration-100 mb-1">{{product.title}}</a>
          <div class="flex items-end gap-2">
            <span class="text-gray-800 lg:text-lg font-bold">{{product.price}}</span>
            <span class="text-red-500 line-through mb-0.5">${{product.price}}</span>
          </div>
        </div>
      </div>     
      {% endfor %}    
      <!-- product - end -->
    </div>
  </div>
</div>
{% endblock body %}

main/templates/main/nav-anim.html
{% load static %}
<nav class="col-span-5 px-2 bg-white dark:bg-gray-900">
   <div class="container flex flex-wrap items-center justify-between mx-auto">
     <a href="{% url 'home-page' %}" class="flex items-center">
         <img src="{% static "main/thuasne.png" %}" class="h-6 mr-3 sm:h-10 animate__animated animate__backInRight animate__delay-1s" alt="Company Logo" />
         <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">KSUshop</span>
     </a>
     <button data-collapse-toggle="navbar-dropdown" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-dropdown" aria-expanded="false">
       <span class="sr-only">Open main menu</span>
       <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
     </button>
     <div class="hidden w-full md:block md:w-auto" id="navbar-dropdown">         
       <ul class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
         <li>
             <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar" class="flex items-center justify-between w-full py-2 pl-3 pr-4 font-medium text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:w-auto dark:text-gray-400 dark:hover:text-white dark:focus:text-white dark:border-gray-700 dark:hover:bg-gray-700 md:dark:hover:bg-transparent">Dropdown <svg class="w-5 h-5 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg></button>
             <!-- Dropdown menu -->
             <div id="dropdownNavbar" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
                 <ul class="py-2 text-sm text-gray-700 dark:text-gray-400" aria-labelledby="dropdownLargeButton">
                   <li>
                     <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Dashboard</a>
                   </li>
                   <li>
                     <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Settings</a>
                   </li>
                   <li>
                     <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Smt</a>
                   </li>
                 </ul>
                 <div class="py-1">
                   <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">Sign out</a>
                 </div>
             </div>
         </li>
         <li>
           <a href="{% url 'add-products-page' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Extra products</a>
         </li>
         <li>
           <a href="{% url "cart:cart_detail" %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Cart</a>
         </li>
         <li>
           <a href="{% url 'contacts-page' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</a>
         </li>
       </ul>
     </div>
   </div>
 </nav>
 <div class="col-span-1 pt-2 space-x-4 bg-white dark:bg-gray-900">
   {% with total_items=cart|length %}
     {% if cart|length > 0 %}
       <div class="inline-block">               
         <a href="{% url "cart:cart_detail" %}">
           <img 
             src="{% static "main/cart.png" %}" 
             class="inline-block h-6 sm:h-10 animate__animated animate__zoomIn" 
             alt="Your have goods in cart" 
             data-bs-toggle="tooltip" 
             data-bs-placement="bottom" 
             title="You have product in cart {{ total_items }}"
           />
           <span class="inline-block">{{ total_items }}</span>             
         </a> 
       </div>                     
     {% else %}
       <div class="inline-block">
         <a href="{% url "cart:cart_detail" %}">
           <img 
             src="{% static "main/cart-empty.png" %}" 
             class="h-6 sm:h-10 animate__animated animate__zoomIn" 
             alt="Your cart is empty."
             data-bs-toggle="tooltip" 
             data-bs-placement="bottom" 
             title="You cart is empty" 
           />
         </a>
       </div>
     {% endif %}
   {% endwith %}      
 </div>
 <div class="col-span-1 pt-2 bg-white dark:bg-gray-900">
   <div class="inline-block">
     <button id="theme-toggle" type="button">          
       <img 
         id="theme-toggle-dark-icon" 
         src="{% static "main/eclipse.png" %}" 
         class="hidden h-6 sm:h-10 animate__animated animate__zoomIn" 
         alt="dark"
         data-bs-toggle="tooltip" 
         data-bs-placement="bottom" 
         title="Click to dark mode" 
       />
       <img 
         id="theme-toggle-light-icon" 
         src="{% static "main/eclipse.png" %}" 
         class="hidden h-6 sm:h-10 animate__animated animate__zoomIn" 
         alt="light"
         data-bs-toggle="tooltip" 
         data-bs-placement="bottom" 
         title="Click to light mode"
       />          
     </button>
   </div>
 </div>

main/templates/main/nav-noanim.html
{% load static %}
<nav class="col-span-5 px-2 bg-white dark:bg-gray-900">
   <div class="container flex flex-wrap items-center justify-between mx-auto">
     <a href="{% url 'home-page' %}" class="flex items-center">
         <img src="{% static "main/thuasne.png" %}" class="h-6 mr-3 sm:h-10" alt="Company Logo" />
         <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">KSUshop</span>
     </a>
     <button data-collapse-toggle="navbar-dropdown" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-dropdown" aria-expanded="false">
       <span class="sr-only">Open main menu</span>
       <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
     </button>
     <div class="hidden w-full md:block md:w-auto" id="navbar-dropdown">         
       <ul class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
         <li>
             <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar" class="flex items-center justify-between w-full py-2 pl-3 pr-4 font-medium text-zinc-700 rounded hover:bg-zinc-500 md:hover:bg-transparent md:border-0 md:hover:text-red-700 md:p-0 md:w-auto dark:text-gray-400 dark:hover:text-white dark:focus:text-white dark:border-gray-700 dark:hover:bg-gray-700 md:dark:hover:bg-transparent">Dropdown <svg class="w-5 h-5 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg></button>
             <!-- Dropdown menu -->
             <div id="dropdownNavbar" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
                 <ul class="py-2 text-sm text-gray-700 dark:text-gray-400" aria-labelledby="dropdownLargeButton">
                   <li>
                     <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Dashboard</a>
                   </li>
                   <li>
                     <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Settings</a>
                   </li>
                   <li>
                     <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Smt</a>
                   </li>
                 </ul>
                 <div class="py-1">
                   <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white">Sign out</a>
                 </div>
             </div>
         </li>
         <li>
           <a href="{% url 'add-products-page' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Extra products</a>
         </li>
         <li>
           <a href="{% url "cart:cart_detail" %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Cart</a>
         </li>
         <li>
           <a href="{% url 'contacts-page' %}" class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Contact</a>
         </li>
       </ul>
     </div>
   </div>
 </nav>
 <div class="col-span-1 pt-2 space-x-4 bg-white dark:bg-gray-900">
   {% with total_items=cart|length %}
     {% if cart|length > 0 %}
       <div class="inline-block">               
         <a href="{% url "cart:cart_detail" %}">
           <img 
             src="{% static "main/cart.png" %}" 
             class="inline-block h-6 sm:h-10" 
             alt="Your have goods in cart" 
             data-bs-toggle="tooltip" 
             data-bs-placement="bottom" 
             title="You have product in cart {{ total_items }}"
           />
           <span class="inline-block">{{ total_items }}</span>             
         </a> 
       </div>                     
     {% else %}
       <div class="inline-block">
         <a href="{% url "cart:cart_detail" %}">
           <img 
             src="{% static "main/cart-empty.png" %}" 
             class="h-6 sm:h-10" 
             alt="Your cart is empty."
             data-bs-toggle="tooltip" 
             data-bs-placement="bottom" 
             title="You cart is empty" 
           />
         </a>
       </div>
     {% endif %}
   {% endwith %}      
 </div>
 <div class="col-span-1 pt-2 bg-white dark:bg-gray-900">
   <div class="inline-block">
     <button id="theme-toggle" type="button">          
       <img 
         id="theme-toggle-dark-icon" 
         src="{% static "main/eclipse.png" %}" 
         class="hidden h-6 sm:h-10 animate__animated animate__zoomIn" 
         alt="dark"
         data-bs-toggle="tooltip" 
         data-bs-placement="bottom" 
         title="Click to dark mode" 
       />
       <img 
         id="theme-toggle-light-icon" 
         src="{% static "main/eclipse.png" %}" 
         class="hidden h-6 sm:h-10 animate__animated animate__zoomIn" 
         alt="light"
         data-bs-toggle="tooltip" 
         data-bs-placement="bottom" 
         title="Click to light mode"
       />          
     </button>
   </div>
 </div>

main/templates/main/product.html
{% extends 'main/base.html' %}
{% block description %}
  <meta name="description" content="Диски Момо">
{% endblock description %}
{% block title %}{{product.title}}{% endblock title %}
{% block nav %}
  {% include 'main/nav-noanim.html' %}
{% endblock nav %}
{% block body %}
<section class="bg-white dark:bg-gray-900">
  <div class="gap-8 items-center py-8 px-4 mx-auto max-w-screen-xl xl:gap-16 md:grid md:grid-cols-2 sm:py-16 lg:px-6">
      <img class="w-3/4 animate__animated animate__backInLeft dark:hidden" src="{{product.img.url}}" alt="dashboard image">
      <div class="mt-4 md:mt-0">
          <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">{{product.title}}</h2>
          <p class="mb-6 font-light text-gray-500 md:text-lg dark:text-gray-400">{{product.description}}</p>
          <span class="hidden">{{product.amount}}</span>
          <span class="text-gray-800 lg:text-lg font-bold">{{product.price}}</span><br>
          <span id="warning" style="color: red;">Not enough goods; Max = {{product.amount}}</span>
          <form action="{% url "cart:cart_add" product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <button 
              id="add_to_cart" 
              type="submit" 
              class="inline-block text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-full text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">
              Add to cart
            </button>
          </form> 
      </div>
  </div>
</section>
<script>
  var select = document.getElementById('id_quantity');
  select.classList.add(
    'inline-block',
    'bg-white', 
    'border-0', 
    'border-b',
    'border-gray-500', 
    'text-gray-900', 
    'text-sm',
    'focus:ring-gray-500',
    'focus:border-gray-500',
    'block',
    'w-1/4',
    'mt-2',
    'p-2.5',
    'dark:bg-gray-700',
    'dark:border-gray-600',
    'dark:placeholder-gray-400',
  );

  var amount = Number(document.getElementsByTagName('span')[2].innerHTML);
  var btn = document.getElementById('add_to_cart');
  var warning = document.getElementById('warning');
  warning.classList.add('hidden');
  
  if (amount == 0) {
    warning.classList.remove('hidden');
    warning.innerHTML = "No goods available";
    btn.classList.add('hidden');
  }

  document.querySelector("select").addEventListener('change', function (e) {
    val = Number(e.target.value);
    if (val <= amount) {
      warning.classList.add('hidden');     
      btn.classList.remove('hidden');      
    }else if(val > amount){
      warning.classList.remove('hidden');
      btn.classList.add('hidden');   
    }
  });
  
</script>
{% endblock body %}